trigger:
  batch: "true"
  branches:
    include: [master, test-*]
  tags:
    include: ["*"]

jobs:
  - template: jobs/python-tests.yml
    parameters:
      coverage: false
      toxenvs: [ py35, py36, py37, py38, py39, py310, pypy3 ]

  - template: jobs/python-tests.yml
    parameters:
      os: windows
      coverage: false
      toxenvs: [ py35, py36, py37, py38, py39, pypy3 ]

  - template: jobs/python-tests.yml
    parameters:
      os: macos
      coverage: false
      toxenvs: [ py35, py36, py37, py38, py39, pypy3 ]

  - template: jobs/pre-commit.yml

  - template: jobs/sphinx-docs.yml

  - template: jobs/npm-build.yml
    parameters:
      artifactName: test-artifact
      artifactPath: testdir

  - template: jobs/npm-build.yml
    parameters:
      artifactName: test-artifact-yarn
      artifactPath: testdir
      namePostfix: _yarn

  - template: jobs/sync-artifact-to-S3.yml
    parameters:
      artifactName: test-artifact
      bucketPath: azure-pipelines-test-bucket
      dependsOn: npm_build
      condition: succeeded()

  - template: jobs/go-tests.yml
    parameters:
      preTest:
        - bash: cp testing-go/* .
          displayName: Hack to make coverage work
      goVersions:
        - "1.13"
        - "1.14"
        - "1.15"

  - template: jobs/go-tests.yml
    parameters:
      os: windows
      preTest:
        - bash: cp testing-go/* .
          displayName: Hack to make coverage work

  - template: jobs/go-tests.yml
    parameters:
      os: osx
      preTest:
        - bash: cp testing-go/* .
          displayName: Hack to make coverage work
