trigger:
  branches:
    include: [master, test-*]
  tags:
    include: ['*']

jobs:
  - template: jobs/python-tests.yml
    parameters:
      coverage: false
      toxenvs: [ py35, py36, py37, py38, py39, pypy3 ]

  - template: jobs/python-tests.yml
    parameters:
      os: windows
      coverage: false
      toxenvs: [ py35, py36, py37, py38, pypy3 ]

  - template: jobs/python-tests.yml
    parameters:
      os: macos
      coverage: false
      toxenvs: [ py35, py36, py37, py38, pypy3 ]

  - template: jobs/pre-commit.yml

  - template: jobs/sphinx-docs.yml
