parameters:
  artifactName: ""
  bucketPath: ""
  dependsOn:
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

jobs:
  - job: upload_artifact_to_S3
    displayName: Upload ${{ parameters.artifactName }} artifact to S3
    dependsOn: ${{ parameters.dependsOn }}
    condition: ${{ parameters.Condition }}

    pool:
      vmImage: ubuntu-18.04

    steps:
      - checkout: none

      - task: DownloadBuildArtifacts@0
        displayName: Download ${{ parameters.artifactName }} artifact
        inputs:
          artifactName: ${{ parameters.artifactName }}
          downloadPath: $(System.DefaultWorkingDirectory)

      - script: |
          sudo apt-get update
          sudo apt-get install awscli
        displayName: Install AWS CLI

      - script: |
          aws s3 sync ${{ parameters.artifactName }} s3://${{ parameters.bucketPath }} --delete
        displayName: Sync artifact to S3
        env:
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
